[package]
name = "rust_telegram_bot"
version = "0.1.0"
authors = ["loo.maclin <loo.maclin@protonmail.com>"]

[dependencies]
telegram-bot = { git = "https://github.com/White-Oak/telegram-bot.git" }
hyper = "0.10.8"
hyper-rustls = "0.3.2"
serde_json = "0.9.10"
serde = "0.9.14"
serde_derive = "0.9.14"